### ISSUE TITLE
Port blocked

### ISSUE THREAD

**Issue by MelisRaimans** [ivanilves/CloudPort#1]
Good morning,

I has a problem in my network, my company firewall does not allow ports, only 80 and 443, so we can not use Cloudport. How can we overcome this obstacle? Thanks!

**Comment by ivanilves** [comment]
Hi,

yes... firewall at some orgs may not like our port choice. This was a matter of time whet it :boom:
I will think how could I escape this. Maybe we should failback to ports `443` or `80` somehow.

**Comment by ivanilves** [comment]
Hey @MelisRaimans 
added failover port 443 functionality to CloudPort and p.t.u.
now the braindead firewall will not stop you that easy!
Deployed on production :sunglasses:

**Comment by MelisRaimans** [comment]
@ivanilves thank you, just saw you made a new CloudPort release. Sorry, I have not notified you before, but it works fine with failover.
