### ISSUE TITLE
greeting

### ISSUE THREAD

**Issue by mcfatealan** [ivanilves/CloudPort#2]
Hi Ivan, thx for your work on CloudPort. This tool is amazing. I'm a college student and apparently a lazy one. Sometimes it's too hard for me to get up and ride my bicycle to the lab. I don't want to mess with our network administrator either. These days I've been thinking setting a proxy on my VPS to enable me to get access to the cluster even at home. But I guess this kind of work should already be implemented by someone awesome, after some digging I found out your repo. Nice job man!

**Comment by ivanilves** [comment]
Thank you, man! I'm happy CloudPort helped you! Such feedback makes me blush from joy. :relaxed: 

If you have any ideas, how to make it better, just tell me. Or, if you could spread the word and introduce CloudPort to anyone, who can also use it and solve some issues with it, that would be also very nice. :wink:

**Comment by mcfatealan** [comment]
Hi @ivanilves , thx for your prompt response. Now I want to further improve my experience of CloudPort, and I really need some of your advice.

Now the situation is  I can successfully use the program generated by cloudport.xyz to expose the private cluster to public. But the thing is my access to the server of cloudport.xyz has high latency, so I want to set up my own server using CloudPort or directly using ptu. I tried both, and I'm quite confused by the issue.

For ptu, I installed in on my machine under the subnet. I never tried Go before so when I ran into this:
```
mcfatealan@mcfatealan-desktop:~/ptu$ ./script/install
Installing dependencies...
# github.com/golang/lint
../.gvm/pkgsets/go1.5.1/global/src/github.com/golang/lint/lint.go:249: undefined: types.ImportMode
```
I have no idea how to solve this. BTW, I installed Go1.5.1 by binaries.



For CloudPort, I installed in on my VPS, and I met an issue that 
```
root@localhost:~/CloudPort# ./script/provision local

* Deploy: master

sudo: dmidecode: command not found
[BOOTSTRAP ERROR] Should be deployed only on virtual machines!
```
Why does this have to work on virtual machines? That's kinda weird to me....

Thanks for your reading! If you have time, could you please suggest some simple suggestions for my situation? Thx!

**Comment by mcfatealan** [comment]
Hi @ivanilves , I did some workaround to pass the `Virtual Machine` test. Now I already installed CloudPort on my VPS.

```
PLAY RECAP *********************************************************************
localhost                  : ok=52   changed=1    unreachable=0    failed=0

```
The thing is that now how do I make sure the service is successfully running? I tried to access the url "[ip]:80", but it gave me nginx 502 error.

```
root@localhost:~/CloudPort# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 00:17 ?        00:00:11 init
root         2     1  0 00:17 ?        00:00:00 [kthreadd/200887]
root         3     2  0 00:17 ?        00:00:00 [khelper/200887]
root       437     1  0 00:17 ?        00:00:00 cron
root       564     1  0 00:21 ?        00:00:00 sshd: root@pts/0
root       575   564  0 00:21 pts/0    00:00:00 -bash
root       822     1  0 00:23 ?        00:00:01 upstart-file-bridge --daemon
root       825     1  0 00:23 ?        00:00:01 upstart-socket-bridge --daemon
root      1797     1  0 00:59 ?        00:00:00 nginx: master process /usr/sbin/nginx
redis     2278     1  0 00:59 ?        00:00:00 /usr/bin/redis-server 127.0.0.1:6379
root      6343   575  0 00:30 pts/0    00:00:02 /usr/bin/python /usr/local/bin/ssserver -c /etc/shadowsocks/config.json
root      8158 28910  0 01:17 ?        00:00:00 sshd: root@pts/2
root      8542  8158  0 01:17 pts/2    00:00:00 -bash
root     11753     1  0 01:05 pts/0    00:00:00 /bin/bash /usr/bin/mysqld_safe
root     11754     1  0 01:05 pts/0    00:00:00 logger -p daemon.err -t /etc/init.d/mysql -i
mysql    12104 11753  0 01:05 pts/0    00:00:01 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql
www-data 14064  1797  0 01:05 ?        00:00:00 nginx: worker process
www-data 14065  1797  0 01:05 ?        00:00:00 nginx: worker process
www-data 14066  1797  0 01:05 ?        00:00:00 nginx: worker process
www-data 14067  1797  0 01:05 ?        00:00:00 nginx: worker process
root     15751     1  0 01:57 ?        00:00:00 /usr/bin/dockerd --raw-logs
root     15759 15751  0 01:57 ?        00:00:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0
root     15766   575  0 01:57 pts/0    00:00:00 ps -ef
root     24784     1  0 00:58 ?        00:00:00 rpcbind -w
root     24959     1  0 00:58 ?        00:00:00 /lib/systemd/systemd-udevd --daemon
root     28910     1  0 00:59 ?        00:00:00 /usr/sbin/sshd -D
root@localhost:~/CloudPort# netstat -tunelp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 45.78.34.34:443         0.0.0.0:*               LISTEN      0          3483056859  6343/python
tcp        0      0 0.0.0.0:26335           0.0.0.0:*               LISTEN      0          3485306073  28910/sshd
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      111        3485757768  12104/mysqld
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      110        3485343649  2278/redis-server 1
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      0          3485292119  24784/rpcbind
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          3485338342  1797/nginx
tcp6       0      0 :::26335                :::*                    LISTEN      0          3485306075  28910/sshd
tcp6       0      0 :::111                  :::*                    LISTEN      0          3485292122  24784/rpcbind
udp        0      0 0.0.0.0:111             0.0.0.0:*                           0          3485292115  24784/rpcbind
udp        0      0 0.0.0.0:791             0.0.0.0:*                           0          3485292118  24784/rpcbind
udp        0      0 0.0.0.0:56374           0.0.0.0:*                           0          3483056861  6343/python
udp        0      0 45.78.34.34:443         0.0.0.0:*                           0          3483056860  6343/python
udp6       0      0 :::111                  :::*                                0          3485292120  24784/rpcbind
udp6       0      0 :::791                  :::*                                0          3485292121  24784/rpcbind
root@localhost:~/CloudPort# restart cloudport
restart: Unknown instance:
```

**Comment by ivanilves** [comment]
Hey @mcfatealan

1.
Please tell me your OS distribution. I suppose you run Ubuntu 14.04 64bit, but just in case.

2.
Please copy/paste here the output of `ansible --version` command.

3.
Also please GZIP and attach here:
* `/var/log/cloudport` - all the directory, plz tar/gzip it
* `/var/log/upstart/cloudport.log`
* `/var/log/upstart/sidekiq.log`

This would be enough to start troubleshooting. :wink:

**Comment by mcfatealan** [comment]
Hi @ivanilves , thx for your concern!
The outputs are listed here:

1. Yes, I specially reinstalled my VPS before trying CloudPort, making sure it's exactly the OS required.
```
root@localhost:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:   	Ubuntu 14.04.5 LTS
Release:       	14.04
Codename:      	trusty
```

2.
```
root@localhost:~# ansible --version
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

3.
The weird thing is there is nothing under this directory (empty directory). And there is no `/var/log/upstart/cloudport.log` or `/var/log/upstart/sidekiq.log` (file non-exist)

**Comment by mcfatealan** [comment]
Should there be a `cloudport` service? I didn't see one.
```
root@localhost:/var/log# service  --status-all
 [ - ]  apache2
 [ - ]  apparmor
 [ - ]  bind9
 [ ? ]  console-setup
 [ + ]  cron
 [ - ]  docker
 [ - ]  fetchmail
 [ - ]  keymap.sh
 [ ? ]  killprocs
 [ ? ]  kmod
 [ ? ]  modules_dep.sh
 [ ? ]  mysql
 [ ? ]  networking
 [ + ]  nginx
 [ - ]  nmbd
 [ ? ]  ondemand
 [ - ]  postfix
 [ - ]  procps
 [ + ]  quota
 [ - ]  quotarpc
 [ ? ]  rc.local
 [ + ]  redis-server
 [ + ]  rpcbind
 [ - ]  rsync
 [ - ]  rsyslog
 [ - ]  samba
 [ - ]  samba-ad-dc
 [ - ]  saslauthd
 [ ? ]  screen-cleanup
 [ ? ]  sendsigs
 [ - ]  smbd
 [ + ]  ssh
 [ - ]  sudo
 [ + ]  udev
 [ ? ]  umountfs
 [ ? ]  umountnfs.sh
 [ ? ]  umountroot
 [ - ]  unattended-upgrades
 [ - ]  urandom
 [ ? ]  vzquota
 [ - ]  wide-dhcpv6-client
 [ - ]  x11-common
 [ - ]  xinetd
```

**Comment by mcfatealan** [comment]
I also tried the continuous integration suite:
```
root@localhost:~/CloudPort# ./script/ci
rake aborted!
Mysql2::Error: Access denied for user 'cloudport'@'localhost' (using password: YES)
/usr/local/rvm/gems/ruby-2.2.5/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `connect'
/usr/local/rvm/gems/ruby-2.2.5/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `initialize'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/migration.rb:916:in `initialize'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `new'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/rvm/gems/ruby-2.2.5/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by ivanilves** [comment]
Hi,

> 2.6.32-042stab113.17

Really nice suggestion! Some `2.6.32` have backported Docker, while some not...
Could you try to create Docker container manually on this VPS and see if it works?

What kind of virtualization uses your VPS?

Do you have `/etc/init/cloudport.conf` file?
Could you do `sudo start cloudport` ? And `dmesg | tail` if it fails?
Will `/var/log/upstart/cloudport.log` appear after running `sudo start cloudport` ?

Thank you!

## P.S.:
> Should there be a cloudport service? I didn't see one.

Not an issue, the CloudPort uses Upstart, but `service` command is up to old System V.

> root@localhost:~/CloudPort# ./script/ci

Yeah, it for run with Rails testing environment, so it's OK for it to fail.

**Comment by mcfatealan** [comment]
Hi @ivanilves , first, thanks for offering me so much advice!

I guess the most important issue is that the default kernel is too old to run docker, this info found in `/var/log/upstart/docker.log`:
```
time="2016-10-06T01:04:45.053884951-04:00" level=fatal msg="Your Linux kernel version 2.6.32-042stab113.17 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer."
```

My VPS provider is [bandwagon](https://bandwagonhost.com) (no I'm not doing Ads XD ). They use OpenVZ.

I have `/etc/init/cloudport.conf`, and it looks good.
I tried to `sudo start cloudport`,  and it failed. The funny thing is that `dmesg | tail` gives me no output...
There is no `/var/log/upstart/cloudport.log` even after trying that.

I guess I should first update my kernel first :) I'll come to you after that, thx man!

**Comment by mcfatealan** [comment]
Errr... I found a post saying that you cannot compile and install your own kernel on OpenVZ... http://serverfault.com/questions/586171/cant-update-linux-kernel-on-vps
I tried hard yesterday, and got unexpectedly failure. I guess that's why.

**Comment by ivanilves** [comment]
Hey @mcfatealan 

Here are things we need to point out:
* Go 1.5.1 became defacto deprecated and broken these days.
* U need to have Go 1.4 installed to build further versions of Go.

So we need to build **p.t.u.** with golang 1.7.1. I've updated installation doc:
https://github.com/ivanilves/ptu/blob/master/doc/Install.md
Also you will need tailoring  doc:
https://github.com/ivanilves/ptu/blob/master/doc/Tailor.md

P.S.:
To run every, even silent script with some output, invoke it with `bash -x script_name`, e.g. `bash -x ./script/install`

**Comment by mcfatealan** [comment]
Hey @ivanilves , you are so great!  I tried a little bit and I could see things are moving on. I have to go catching the night bus now and I'll test this tomorrow. Thx again!

**Comment by mcfatealan** [comment]
Hey @ivanilves , I succeeded! Now I could get access to the lab cluster by ssh to my VPS first. It's really really cool. Thanks so much for your help and advice these days. I really appreciate your kindness.

Here I'd like to share some of my experience for people who are in the similar occasions and looks for convenient solutions.

First, the big picture is:
home ==>  VPS ==> my personal machine in the lab ==> lab cluster
except my VPS, they don't have a valid ip to the public.

I've tried the following solutions:
1.ssh tunnel (remote port forwarding), this could be the straight forward solution. The thing is the tunnel is not stable, you cannot expect the tunnel is still there after driving home.
2.using cloudport.xyz, this one is the most efficient, but the latency could suffer (or not, I'm in China so the latency is quite annoying) 
3.set up my own CloudPort on my VPS, this sounds cool, but it's a little complex and on some VPS using OpenVZ, the kernel is quite old and what's worse you cannot modify it, making docker unavailable.
4.simply use ptu. Thx @ivanilves updating the doc, I could set up one in several minutes. And the latency is satisfying.

**Comment by mcfatealan** [comment]
Err... I met a new problem, the connection will unexpectedly drop as ssh tunnel does. And ptu shows no output for the disconnection. Is there any solution?

**Comment by ivanilves** [comment]
Hey @mcfatealan 

I understand you. That's great you are examining all in details :ok_hand: :clap: 

This is really strange... There are no errors displayed? How much time passes between (approximately) between you start ptu and the tunnel gets disconnected? Does restarting the ptu restores the forwarded connection? 

I mean ptu used to reconnect indefinitely. And it should display errors on dropped tunnel / something.

**Comment by mcfatealan** [comment]
Well, this is ptu log
```
-------------------------------------------------------------------------------
> ptu v0.5.0 "Amante Latino"
--------------------------------------------------------------------------------
2016/10/10 17:02:01 [OK] SSH tunnel initialized!
--------------------------------------------------------------------------------
Build ID    : chang-b20161008-142238-28847
Target host : 10.0.0.100:22
--------------------------------------------------------------------------------

CONNECT HERE: 45.78.34.34:16725

[ Examples ]
    SSH : ssh -p 16725 45.78.34.34
   SFTP : sftp -oPort=16725 45.78.34.34
    RDP : rdesktop 45.78.34.34:16725
   HTTP : curl http://45.78.34.34:16725/
  HTTPS : curl -k https://45.78.34.34:16725/
--------------------------------------------------------------------------------
2016/10/10 17:02:30 [CONN] From: 202.120.40.82:64148 | Forward: 192.168.10.19:57814 => 10.0.0.100:22
2016/10/10 17:06:05 [CONN] From: 202.120.40.82:64181 | Forward: 192.168.10.19:57816 => 10.0.0.100:22
```

The time period might be half a hour? I guess.
After that: 
```
  % ssh -p 16725 chlou@45.78.34.34                                                                                                                                             
ssh: connect to host 45.78.34.34 port 16725: Connection refused
```

Restarting is no use. And on my VPS you can see that port is no longer listening by `netstat -tunelp`.

**Comment by ivanilves** [comment]
@mcfatealan 

I've tested myself, works pretty stable for me for > 4 hours.

Could you please:
1) Try to run it on your own machine (to see if the :bug: happens also outside your VPS)
2) Try to compile the the code with previous version of Go: 
```
gvm install go1.6.3
gvm use go1.6.3 --default
```
and the re-compile re-tailor the p.t.u. ?

Thank you!

**Comment by ivanilves** [comment]
OK, no interest from my peer, closing :grin: :wave:

**Comment by mcfatealan** [comment]
Hi @ivanilves , sorry for the late response, it's just that I've been busy preparing some work stuff for the last two weeks, so I didn't send the result back to you immediately. Actually I tested it on my own machine one week ago, and it's quite steady -- one day without disconnection, I guess the VPS is to blame. At that time I thought the test is not enough, so I didn't immediately post it here.

**Comment by mcfatealan** [comment]
The biggest problem for me is nothing to do with your codes -- it's the unsteadiness of VPS and the high latency (my VPS is located on LA, so still facing difficult experience). At last I used one of our lab machines as a springboard to do ssh-tunnel. It's not cool as what you did, but it suits my situation best. 

Thanks so much for your help all the time, really :D

**Comment by ivanilves** [comment]
Ah! Good to know you have working solution! :clap: :clap: :clap: 

Anyway you are welcome to use p.t.u./CloudPort whenever you need it 
and also recommend it to your peers if they need some thing like this! :wink: 

Thank you!
