### ISSUE TITLE
Am I understanding this?

### ISSUE THREAD

**Issue by kevjonesin** [ivanilves/CloudPort#3]
Hi Ivan, I'm Kevin Jones, I just came across your github page (was looking into VyOS and googled "vybuddy" and found a link to you). Anyway, I'm quite intrigued but as a home hobbyist hack—rather than a 1337 h@X0r—I'd like to ask some questions. 

Am I understanding correctly that if I enter the static lease/ LAN IP (192.168.1.XX) and SSH port # of a 32 bit home Debian box into the wizard at *cloudport.xyz* and record the resulting *"cloudport.xyz:XXXXX"* custom port URL and download the associated *"ptu-linux-386-XXXXXX"* file and run it as an executable on the relevant Debian box in my home LAN behind my ISP's gateway router firewall I'll then be able to go over to my brother's house and access it via SSH from his LAN (or wherever) with *"MyLocalUser@cloudport.xyz:XXXXXX"* without needing to set up any explicit pinholes/port-forwarding on my home router? Where *"MyLocalUser"* is an established username on my relevant home Debian system? 

Also – if such is indeed the case – how long will *"cloudport.xyz:XXXXX"* provide a link to run SSH from outside my home LAN to *"MyLocalUser@192.168.1.XX"*? Do the links expire? Can they be used multiple times? 

I presume if I were to reboot my local Debian system I'd need to run the *"ptu-linux-386-XXXXXX"* executable again to refresh external access through *"cloudport.xyz:XXXXX"*? Would the executable have to be run again locally if only my local router was rebooted (but not the Debian box itself)? 

Thanks-in-advance for your time and attention, Ivan. I look forward to experiencing some of your creations.

p.s.— I'm now following `@ivanilves` on twitter via `@kevjonesin` (follow me back and PM if it would be useful to discuss actual IPs, URLs, and ports without obfuscation).  :  }

**Comment by ivanilves** [comment]
Hi @kevjonesin !

Yes you got it right, `cloudport.xyz` will have a port proxied to your local box.
You can also point `cloudport` to `127.0.0.1`, if you will run `ptu` binary on the same box you want access to.

Currently 28 days is a maximum lifetime for a tunnel.
Tunnels that were created, but never used, are destroyed after 7 days.

**Comment by kevjonesin** [comment]
Hmm, I tried running the custom executable from the cloudport.xyz wizard on my local box both as normal user and as root and in both cases received repeating error messages as so:
`2017/07/30 17:22:25 Error initializing SSH tunnel: ssh: tcpip-forward request denied by peer (will retry)
2017/07/30 17:22:32 * Will try failover server: cloudport.xyz:443
2017/07/30 17:22:34 Error initializing SSH tunnel: ssh: tcpip-forward request denied by peer (will retry)
2017/07/30 17:22:41 Error initializing SSH tunnel: ssh: tcpip-forward request denied by peer (will retry)
2017/07/30 17:22:46 * Will try failover server: cloudport.xyz:443
...`

**Comment by ivanilves** [comment]
![image](https://user-images.githubusercontent.com/9897741/28765932-7952c402-75cd-11e7-8ffd-063221d962ad.png)

**Comment by ivanilves** [comment]
Hey I've tried your build and it worked :wink: 

Maybe there is some blocking firewall or proxy rules in your network impeding you to connect?

**Comment by ivanilves** [comment]
closed due to inactivity
